language: php

php:
  - '7.0'

before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'

before_script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
  - mkdir -p bootstrap/cache
  - mkdir -p storage/app
  - mkdir -p storage/framework/sessions
  - mkdir -p storage/framework/cache
  - mkdir -p storage/framework/views
  - chmod 777 -R storage
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/squizlabs/php_codesniffer/bin/phpcs -n -q
  - vendor/bin/phpunit

services:
  - mysql

branches:
  only:
    - master